spring:
  datasource:
    url: jdbc:sqlserver://cavalcanti.database.windows.net:1433;database=c134002db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: leocavalcanti
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    dialect : org.hibernate.dialect.SQLServerDialect

server:
  port: 9191


